name: Random Commits

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:      # allow manual trigger

jobs:
  random-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run random commits script
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_PAT: ${{ secrets.GH_PAT }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
        run: |
          echo "GH_USER=$GH_USER"
          echo "GH_PAT is set? [${{ secrets.GH_PAT != '' }}]"
          echo "TARGET_REPO is set? [${{ secrets.TARGET_REPO != '' }}]"
          python3 random_commits.py
