name: Random Commits Bot

on:
  schedule:
    - cron: '30 12 * * *' # runs every day at 12:30 UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  random-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout orchestrator repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run random commits
        env:
          GITHUB_USER: ${{ secrets.GH_USER }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: python3 random_commits.py
